disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Nikush Patel"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Nikush Patel"
#   email = "youremail@example.com"
#   image = "profile.jpg"
#   imageQuality = 96
  headline = "I have no idea what I'm doing"
  bio = "I have no idea what I'm doing"
#   links = [
#     { email = "mailto:hello@your_domain.com" },
#     { github = "https://github.com/nikush" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#   ]
